apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.gpu.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "test-server-chart.deployment.gpu-tester.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.gpu.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-server-chart.deployment.gpu-tester.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-server-chart.deployment.gpu-tester.labels" . | nindent 8 }}
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: {{ .Values.deployment.gpu.name }}
        image: {{ .Values.deployment.gpu.image }}
        ports:
        - containerPort: {{ .Values.deployment.gpu.port }}
        volumeMounts:
        - mountPath: {{ .Values.deployment.gpu.volume.mountPath}}
          name: {{ .Values.deployment.gpu.volume.name }}
      volumes:
      - name: {{ .Values.deployment.gpu.volume.name }}
        nfs:
          server: {{ .Values.deployment.gpu.volume.server }}
          path: {{ .Values.deployment.gpu.volume.path }}